lib/image_hub_web/router.ex
defmodule ImageHubWeb.Router do
  use ImageHubWeb, :router

  pipeline :auth do
    plug ImageHub.Accounts.Pipeline
    plug :put_user_token
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", ImageHubWeb do
    pipe_through([:browser])

    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :callback)
    post("/:provider/callback", AuthController, :callback)
    post("/logout", AuthController, :delete)
  end

  scope "/", ImageHubWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index


    # session
    get  "/login",  SessionController, :new
    get  "/logout", SessionController, :logout
    post "/login",  SessionController, :login
    get "/sign_up", UserController, :new
    post "/users", UserController, :create
    get "/videos", VideoController, :index
    get "/watch/:id", WatchController, :show
  end

  scope "/", ImageHubWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/protected", PageController, :protected
    resources "/users", UserController
    resources "/uploads", UploadController
    resources "/videos", VideoController
  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end
  # Other scopes may use custom stacks.
  # scope "/api", ImageHubWeb do
  #   pipe_through :api
  # end
end

lib/image_hub_web/views/layout_view.ex
defmodule ImageHubWeb.LayoutView do
  use ImageHubWeb, :view
end

lib/image_hub_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "ImageHub · Phoenix Framework" %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
    <script>window.userToken = "<%= assigns[:user_token] %>";</script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
          <%= if @current_user do %>
            <li><a href="<%= Routes.session_path(@conn, :logout) %>">Logout</a></li>
          <% else %>
            <li><a href="<%= Routes.session_path(@conn, :login) %>">Login</a></li>
          <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>