lib/image_hub_web/router.ex
defmodule ImageHubWeb.Router do
  use ImageHubWeb, :router

  pipeline :auth do
    plug ImageHub.Accounts.Pipeline
    plug :put_user_token
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", ImageHubWeb do
    pipe_through([:browser])

    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :callback)
    post("/:provider/callback", AuthController, :callback)
    post("/logout", AuthController, :delete)
  end

  scope "/", ImageHubWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index


    # session
    get  "/login",  SessionController, :new
    get  "/logout", SessionController, :logout
    post "/login",  SessionController, :login
    get "/sign_up", UserController, :new
    post "/users", UserController, :create
    get "/videos", VideoController, :index
    get "/watch/:id", WatchController, :show
  end

  scope "/", ImageHubWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/protected", PageController, :protected
    resources "/users", UserController
    resources "/uploads", UploadController
    resources "/videos", VideoController
  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end
  # Other scopes may use custom stacks.
  # scope "/api", ImageHubWeb do
  #   pipe_through :api
  # end
end

lib/image_hub_web/controllers/watch_controller.ex
defmodule ImageHubWeb.WatchController do
  use ImageHubWeb, :controller
  alias ImageHub.Multimedia

  def show(conn, %{"id" => id}) do
    video = Multimedia.get_video!(id)
    render(conn, "show.html", video: video)
  end
end

lib/image_hub_web/views/watch_view.ex
defmodule ImageHubWeb.WatchView do
  use ImageHubWeb, :view

  def player_id(video) do
    ~r{^.*(?:youtu\.be/|\w+/|v=)(?<id>[^#&?]*)}
    |> Regex.named_captures(video.url)
    |> get_in(["id"])
  end
end

lib/image_hub_web/templates/watch/show.html.eex
<%= link "More", to: Routes.video_path(@conn, :index) %>
<div class="row">
  <div class="column column-60">
    <h1><%= @video.title %></h1>
    <%= content_tag :div, id: "video", data: [id: @video.id, player_id: player_id(@video)] do %>
    <% end %>
  </div>
  <div class="column annotations">
    <div id="msg-container">
    </div>
    <div>
      <textarea id="msg-input" rows=3></textarea>
      <button type="submit" class="button column" id="msg-submit">Post</button>
    </div>
  </div>
</div>

<hr>

<div class="row">
  <div class="column">
    <h3>User</h3>
    <ul id="user-list"></ul>
  </div>
</div>